spring:
  config.activate.on-profile: dev

  datasource:
    url: jdbc:h2:mem:employee-management-db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2.console.enabled: true
